### ISSUE TITLE
Lighting Update Bug

### ISSUE THREAD

**Issue by dexman545** [Abastro/StellarAPI#3] opened 2016-06-16 14:56 UTC
_From @dexman545 on June 15, 2016 15:25_

Using Stellar Sky 0.4.4.1 and StellarAPI 0.4.3.2b on MC 1.9.4 and Forge 1963

When placing/removing torches near a chunk border, the lighting does not always spread across the chunk border until the adjacent chunk is given a block update.

Images: https://imgur.com/a/1JtZF
The images were taken while other mods were installed, but I have confirmed that this happens with just stellar sky installed.

_Copied from original issue: Abastro/StellarSky#64_

**Comment by dexman545** [comment] 2016-06-16 14:56
_From @Abastro on June 15, 2016 15:54_

Does this happen only with Stellar API?

**Comment by dexman545** [comment] 2016-06-16 14:56
no, it does not appear to happen with just Stellar API

**Comment by dexman545** [comment] 2016-06-16 14:56
_From @Abastro on June 16, 2016 5:36_

Reproduced this bug, only with Stellar API.
Would you migrate this issue to Stellar API?

**Comment by dexman545** [comment] 2016-06-16 14:56
_From @Abastro on June 16, 2016 6:30_

Was a forge bug.
![2016-06-16_15 29 05](https://cloud.githubusercontent.com/assets/5730296/16107422/3ca502ba-33d7-11e6-88c2-52f996d7cffb.png)
https://github.com/MinecraftForge/MinecraftForge/issues/2991

**Comment by Abastro** [comment] 2016-06-20 16:07
It seems that lowering Max FPS framerate is partially solving the problem.
I'll investigate the reason.

**Comment by Abastro** [comment] 2017-07-18 06:40
Duplicate of the Stellar Sky's bug.

**Closed by Abastro** 2017-07-18 06:40 UTC
Labels: bug
